In [1]:
## Standard libraries
import os
import math
import numpy as np
import time

## Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib_inline.backend_inline import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set_theme()

## Progress bar
from tqdm.notebook import tqdm

In [5]:
import torch
print("Using torch", torch.__version__)

Using torch 2.11.0+cu128


In [4]:
torch.manual_seed(42) # Setting the seed

In [36]:
x = torch.Tensor(2, 2 , 2)
print(x)
print(x[0][0][0])
print(x[0][0][1])
print(x[0][1][0])
print(x[0][1][1])
print(x[1][0][0])
print(x[1][0][1])
print(x[1][1][0])
print(x[1][1][1])


tensor([[[-2.4049e-29,  3.0802e-41],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  4.4997e-41],
         [ 6.8664e-44,  0.0000e+00]]])
tensor(-2.4049e-29)
tensor(3.0802e-41)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(4.4997e-41)
tensor(6.8664e-44)
tensor(0.)


In [ ]:
t = torch.Tensor()
print(t)

x = torch.arange(start=2, end=20, step=2, out=t)
print(x)
print(t)
t[0] = 1
x[1] = 3
print(x)
print(t)

tensor([])
tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])
tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])
tensor([ 1.,  3.,  6.,  8., 10., 12., 14., 16., 18.])
tensor([ 1.,  3.,  6.,  8., 10., 12., 14., 16., 18.])


In [ ]:
z = torch.zeros(size=(5,),)
z

tensor([0., 0., 0., 0., 0.])

In [82]:
o = torch.ones(size=(5,),)
o

tensor([1., 1., 1., 1., 1.])

In [91]:
# Create a tensor with random values between 0 and 1 with the shape [2, 3, 4]
x = torch.rand(2, 3, 4)
print(x)

tensor([[[0.0469, 0.5807, 0.8201, 0.8321],
         [0.1021, 0.6779, 0.2152, 0.4805],
         [0.3957, 0.0825, 0.0230, 0.1711]],

        [[0.7269, 0.7287, 0.0651, 0.3122],
         [0.5082, 0.0677, 0.7817, 0.9529],
         [0.5884, 0.1285, 0.6166, 0.6815]]])


In [92]:
shape = x.shape
print("Shape:", x.shape)

size = x.size()
print("Size:", size)

dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [93]:
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]])


In [94]:
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


In [95]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
y = x1 + x2

print("X1", x1)
print("X2", x2)
print("Y", y)

X1 tensor([[0.8959, 0.2340, 0.0520],
        [0.7197, 0.5311, 0.3371]])
X2 tensor([[0.2905, 0.2422, 0.9047],
        [0.4137, 0.8606, 0.9463]])
Y tensor([[1.1864, 0.4762, 0.9568],
        [1.1334, 1.3917, 1.2834]])


In [105]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
print("X1 (before)", x1)
print("X2 (before)", x2)

x3 = x2.add_(x1) # add_ or add
print("X1 (after)", x1)
print("X2 (after)", x2)

print("X3)", x3)

X1 (before) tensor([[0.4408, 0.2735, 0.7100],
        [0.5045, 0.4273, 0.2580]])
X2 (before) tensor([[0.4342, 0.0748, 0.6137],
        [0.5075, 0.8034, 0.5323]])
X1 (after) tensor([[0.4408, 0.2735, 0.7100],
        [0.5045, 0.4273, 0.2580]])
X2 (after) tensor([[0.8750, 0.3483, 1.3237],
        [1.0120, 1.2307, 0.7902]])
X3) tensor([[0.8750, 0.3483, 1.3237],
        [1.0120, 1.2307, 0.7902]])


In [106]:
x = torch.arange(6)
print("X", x)

X tensor([0, 1, 2, 3, 4, 5])


In [110]:
x = x.view(3, 2)
print("X", x)

x = x.view(1, 6)
print("X", x)

X tensor([[0, 1],
        [2, 3],
        [4, 5]])
X tensor([[0, 1, 2, 3, 4, 5]])


In [111]:
x = x.permute(1, 0) # Swapping dimension 0 and 1
print("X", x)

X tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])


In [112]:
x = torch.arange(6)
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [113]:
W = torch.arange(9).view(3, 3) # We can also stack multiple operations in a single line
print("W", W)

W tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [114]:
h = torch.matmul(x, W) # Verify the result by calculating it by hand too!
print("h", h)

h tensor([[15, 18, 21],
        [42, 54, 66]])


In [117]:
x = torch.arange(12).view(3, 4)
print("X", x)

X tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [118]:
print(x[:, 1])   # Second column

tensor([1, 5, 9])


In [119]:
print(x[0])      # First row

tensor([0, 1, 2, 3])


In [133]:
print(x)
print(x[:2, -1]) # First two rows, last column

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([3, 7])


In [139]:
print(x[1:3, :]) # Middle two rows


tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [140]:
x = torch.ones((3,))
print(x.requires_grad)

False


In [141]:
x.requires_grad_(True)
print(x.requires_grad)

True


In [142]:
x = torch.arange(start=2, end=20, step=2, out=t, requires_grad=True)
print(x.requires_grad)

True


In [148]:
print(torch.get_default_dtype())
x = torch.arange(3, dtype=torch.float32, requires_grad=True) # Only float tensors can have gradients
print("X", x)

torch.float32
X tensor([0., 1., 2.], requires_grad=True)


In [149]:
a = x + 2
b = a ** 2
c = b + 3
y = c.mean()
print("Y", y)

Y tensor(12.6667, grad_fn=<MeanBackward0>)


In [150]:
y.backward()

In [151]:
print(x.grad)

tensor([1.3333, 2.0000, 2.6667])


In [3]:
gpu_avail = torch.cuda.is_available()
print(f"Is the GPU available? {gpu_avail}")

Is the GPU available? True


In [6]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print("Device", device)

Device cuda


In [5]:
x = torch.zeros(2, 3)
x = x.to(device)
print("X", x)

X tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')


In [7]:
x = torch.randn(5000, 5000)

In [8]:
## CPU version
start_time = time.time()
_ = torch.matmul(x, x)
end_time = time.time()
print(f"CPU time: {(end_time - start_time):6.5f}s")

## GPU version
x = x.to(device)
_ = torch.matmul(x, x)  # First operation to 'burn in' GPU
# CUDA is asynchronous, so we need to use different timing functions
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)
start.record()
_ = torch.matmul(x, x)
end.record()
torch.cuda.synchronize()  # Waits for everything to finish running on the GPU
print(f"GPU time: {0.001 * start.elapsed_time(end):6.5f}s")  # Milliseconds to seconds

CPU time: 2.11961s
GPU time: 0.07428s


In [9]:
# GPU operations have a separate seed we also want to set
if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    torch.cuda.manual_seed_all(42)

# Additionally, some operations on a GPU are implemented stochastic for efficiency
# We want to ensure that all operations are deterministic on GPU (if used) for reproducibility
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False